// Obras realizadas por Aislaser (fotografías procedentes de la web anterior)

export type Sector = "infraestructuras" | "industria" | "edificacion" | "piscinas" | "residencial" | "tecnicas";

export type ProjectImage = { src: string; width: number; height: number; alt?: string };

export type Project = {
  slug: string;
  title: string;
  location: string;
  sector: Sector;
  /** Sale en «Proyectos que hablan por nosotros» de la portada */
  featured: boolean;
  images: ProjectImage[];
  /** Carpeta de la galería en la web anterior (para redirecciones 301) */
  legacy?: string;
  /** Campos que se rellenan desde el panel (obras de la base de datos) */
  year?: string;
  summary?: string;
  description?: string;
  /** Slugs de los servicios relacionados */
  services?: string[];
};

export const sectors: Record<Sector, { label: string; short: string }> = {
  infraestructuras: { label: "Infraestructuras y obra pública", short: "Infraestructuras" },
  industria: { label: "Industria, energía y comercio", short: "Industria y energía" },
  edificacion: { label: "Edificación pública y singular", short: "Edificación" },
  piscinas: { label: "Piscinas, depósitos y balsas", short: "Piscinas y depósitos" },
  residencial: { label: "Residencial", short: "Residencial" },
  tecnicas: { label: "Técnicas especiales", short: "Técnicas especiales" },
};

export const projects: Project[] = [
  {
    slug: "aeropuerto-de-bilbao",
    title: "Aeropuerto de Bilbao",
    location: "Bilbao (Bizkaia)",
    sector: "infraestructuras",
    featured: false,
    legacy: "aeropuertobilbao",
    images: [
      { src: "/images/obras/aeropuerto-de-bilbao/01.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-bilbao/02.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-bilbao/03.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-bilbao/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "aeropuerto-de-malaga",
    title: "Aeropuerto de Málaga",
    location: "Málaga",
    sector: "infraestructuras",
    featured: false,
    legacy: "aeropuertomalaga",
    images: [
      { src: "/images/obras/aeropuerto-de-malaga/01.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-malaga/02.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-malaga/03.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-malaga/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "aeropuerto-de-sevilla-t1",
    title: "Aeropuerto de Sevilla T1",
    location: "Sevilla",
    sector: "infraestructuras",
    featured: true,
    legacy: "aeropuertosevilla1",
    images: [
      { src: "/images/obras/aeropuerto-de-sevilla-t1/01.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-sevilla-t1/02.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-sevilla-t1/03.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-sevilla-t1/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "aeropuerto-de-sevilla-t2",
    title: "Aeropuerto de Sevilla T2",
    location: "Sevilla",
    sector: "infraestructuras",
    featured: false,
    legacy: "aeropuertosevilla2",
    images: [
      { src: "/images/obras/aeropuerto-de-sevilla-t2/01.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-sevilla-t2/02.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-sevilla-t2/03.webp", width: 720, height: 480 },
      { src: "/images/obras/aeropuerto-de-sevilla-t2/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "terminal-de-carga-de-malaga",
    title: "Terminal de Carga de Málaga",
    location: "Málaga",
    sector: "infraestructuras",
    featured: false,
    legacy: "terminalcargamalaga",
    images: [
      { src: "/images/obras/terminal-de-carga-de-malaga/01.webp", width: 720, height: 480 },
      { src: "/images/obras/terminal-de-carga-de-malaga/02.webp", width: 720, height: 480 },
      { src: "/images/obras/terminal-de-carga-de-malaga/03.webp", width: 720, height: 480 },
      { src: "/images/obras/terminal-de-carga-de-malaga/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "ave-alta-velocidad",
    title: "AVE Alta Velocidad",
    location: "",
    sector: "infraestructuras",
    featured: false,
    legacy: "avealtavelocidad",
    images: [
      { src: "/images/obras/ave-alta-velocidad/01.webp", width: 720, height: 480 },
      { src: "/images/obras/ave-alta-velocidad/02.webp", width: 720, height: 480 },
      { src: "/images/obras/ave-alta-velocidad/03.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "conibridge-cordoba",
    title: "Conibridge Córdoba",
    location: "Córdoba",
    sector: "infraestructuras",
    featured: true,
    legacy: "conibridge",
    images: [
      { src: "/images/obras/conibridge-cordoba/01.webp", width: 720, height: 480 },
      { src: "/images/obras/conibridge-cordoba/02.webp", width: 720, height: 480 },
      { src: "/images/obras/conibridge-cordoba/03.webp", width: 720, height: 480 },
      { src: "/images/obras/conibridge-cordoba/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "confederacion-hidrografica",
    title: "Confederación Hidrográfica",
    location: "",
    sector: "infraestructuras",
    featured: false,
    legacy: "confederacionhidrografica",
    images: [
      { src: "/images/obras/confederacion-hidrografica/01.webp", width: 720, height: 480 },
      { src: "/images/obras/confederacion-hidrografica/02.webp", width: 720, height: 480 },
      { src: "/images/obras/confederacion-hidrografica/03.webp", width: 720, height: 480 },
      { src: "/images/obras/confederacion-hidrografica/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "central-nuclear-de-almaraz",
    title: "Central Nuclear de Almaraz",
    location: "Almaraz (Cáceres)",
    sector: "industria",
    featured: false,
    legacy: "almaraz",
    images: [
      { src: "/images/obras/central-nuclear-de-almaraz/01.webp", width: 720, height: 480 },
      { src: "/images/obras/central-nuclear-de-almaraz/02.webp", width: 720, height: 480 },
      { src: "/images/obras/central-nuclear-de-almaraz/03.webp", width: 720, height: 480 },
      { src: "/images/obras/central-nuclear-de-almaraz/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "central-termica-de-algeciras",
    title: "Central Térmica de Algeciras",
    location: "Algeciras (Cádiz)",
    sector: "industria",
    featured: true,
    legacy: "centraltermicaalgeciras",
    images: [
      { src: "/images/obras/central-termica-de-algeciras/01.webp", width: 720, height: 480 },
      { src: "/images/obras/central-termica-de-algeciras/02.webp", width: 720, height: 480 },
      { src: "/images/obras/central-termica-de-algeciras/03.webp", width: 720, height: 480 },
      { src: "/images/obras/central-termica-de-algeciras/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "bodegas-williams-humbert",
    title: "Bodegas Williams & Humbert",
    location: "Jerez de la Frontera (Cádiz)",
    sector: "industria",
    featured: false,
    legacy: "bodegaswilliams",
    images: [
      { src: "/images/obras/bodegas-williams-humbert/01.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/02.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/03.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/04.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/05.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/06.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/07.webp", width: 720, height: 480 },
      { src: "/images/obras/bodegas-williams-humbert/08.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "cetarsa",
    title: "Cetarsa",
    location: "",
    sector: "industria",
    featured: false,
    legacy: "cetarsa",
    images: [
      { src: "/images/obras/cetarsa/01.webp", width: 720, height: 480 },
      { src: "/images/obras/cetarsa/02.webp", width: 720, height: 480 },
      { src: "/images/obras/cetarsa/03.webp", width: 720, height: 480 },
      { src: "/images/obras/cetarsa/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "burger-king",
    title: "Burger King",
    location: "",
    sector: "industria",
    featured: false,
    legacy: "burgerking",
    images: [
      { src: "/images/obras/burger-king/01.webp", width: 720, height: 480 },
      { src: "/images/obras/burger-king/02.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "hospital-de-huelva",
    title: "Hospital de Huelva",
    location: "Huelva",
    sector: "edificacion",
    featured: true,
    legacy: "hospitalhuelva",
    images: [
      { src: "/images/obras/hospital-de-huelva/01.webp", width: 720, height: 480 },
      { src: "/images/obras/hospital-de-huelva/02.webp", width: 720, height: 480 },
      { src: "/images/obras/hospital-de-huelva/03.webp", width: 720, height: 480 },
      { src: "/images/obras/hospital-de-huelva/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "palacio-de-congresos-villanueva-de-la-serena",
    title: "Palacio de Congresos de Villanueva de la Serena",
    location: "Villanueva de la Serena (Badajoz)",
    sector: "edificacion",
    featured: true,
    legacy: "palaciocongresos",
    images: [
      { src: "/images/obras/palacio-de-congresos-villanueva-de-la-serena/01.webp", width: 720, height: 480 },
      { src: "/images/obras/palacio-de-congresos-villanueva-de-la-serena/02.webp", width: 720, height: 480 },
      { src: "/images/obras/palacio-de-congresos-villanueva-de-la-serena/03.webp", width: 720, height: 480 },
      { src: "/images/obras/palacio-de-congresos-villanueva-de-la-serena/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "ifepa-murcia",
    title: "IFEPA Murcia",
    location: "Murcia",
    sector: "edificacion",
    featured: false,
    legacy: "ifepamurcia",
    images: [
      { src: "/images/obras/ifepa-murcia/01.webp", width: 720, height: 480 },
      { src: "/images/obras/ifepa-murcia/02.webp", width: 720, height: 480 },
      { src: "/images/obras/ifepa-murcia/03.webp", width: 720, height: 480 },
      { src: "/images/obras/ifepa-murcia/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "iglesia-en-badajoz",
    title: "Iglesia en Badajoz",
    location: "Badajoz",
    sector: "edificacion",
    featured: false,
    legacy: "iglesiabadajoz",
    images: [
      { src: "/images/obras/iglesia-en-badajoz/01.webp", width: 720, height: 480 },
      { src: "/images/obras/iglesia-en-badajoz/02.webp", width: 720, height: 480 },
      { src: "/images/obras/iglesia-en-badajoz/03.webp", width: 720, height: 480 },
      { src: "/images/obras/iglesia-en-badajoz/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "caja-de-badajoz",
    title: "Caja de Badajoz",
    location: "Badajoz",
    sector: "edificacion",
    featured: false,
    legacy: "cajabadajoz",
    images: [
      { src: "/images/obras/caja-de-badajoz/01.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "cuartel-cibeles",
    title: "Cuartel Cibeles",
    location: "",
    sector: "edificacion",
    featured: false,
    legacy: "cuartelcibeles",
    images: [
      { src: "/images/obras/cuartel-cibeles/01.webp", width: 720, height: 480 },
      { src: "/images/obras/cuartel-cibeles/02.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "albergue-militar",
    title: "Albergue Militar",
    location: "",
    sector: "edificacion",
    featured: false,
    legacy: "alberguemilitar",
    images: [
      { src: "/images/obras/albergue-militar/01.webp", width: 720, height: 480 },
      { src: "/images/obras/albergue-militar/02.webp", width: 720, height: 480 },
      { src: "/images/obras/albergue-militar/03.webp", width: 720, height: 480 },
      { src: "/images/obras/albergue-militar/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "centro-de-piraguismo-alange",
    title: "Centro de Piragüismo de Alange",
    location: "Alange (Badajoz)",
    sector: "edificacion",
    featured: false,
    legacy: "centropiraguismoalange",
    images: [
      { src: "/images/obras/centro-de-piraguismo-alange/01.webp", width: 720, height: 480 },
      { src: "/images/obras/centro-de-piraguismo-alange/02.webp", width: 720, height: 480 },
      { src: "/images/obras/centro-de-piraguismo-alange/03.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "conideck-boadilla",
    title: "Conideck Boadilla",
    location: "Boadilla del Monte (Madrid)",
    sector: "edificacion",
    featured: false,
    legacy: "conideckboadilla",
    images: [
      { src: "/images/obras/conideck-boadilla/01.webp", width: 720, height: 480 },
      { src: "/images/obras/conideck-boadilla/02.webp", width: 720, height: 480 },
      { src: "/images/obras/conideck-boadilla/03.webp", width: 720, height: 480 },
      { src: "/images/obras/conideck-boadilla/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "conideck-salamanca",
    title: "Conideck Salamanca",
    location: "Salamanca",
    sector: "edificacion",
    featured: false,
    legacy: "conidecksalamanca",
    images: [
      { src: "/images/obras/conideck-salamanca/01.webp", width: 720, height: 480 },
      { src: "/images/obras/conideck-salamanca/02.webp", width: 720, height: 480 },
      { src: "/images/obras/conideck-salamanca/03.webp", width: 720, height: 480 },
      { src: "/images/obras/conideck-salamanca/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "valladolid",
    title: "Graderío en Valladolid",
    location: "Valladolid",
    sector: "edificacion",
    featured: false,
    legacy: "valladolid",
    images: [
      { src: "/images/obras/valladolid/01.webp", width: 720, height: 480 },
      { src: "/images/obras/valladolid/02.webp", width: 720, height: 480 },
      { src: "/images/obras/valladolid/03.webp", width: 720, height: 480 },
      { src: "/images/obras/valladolid/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "piscina-de-cordoba",
    title: "Piscina de Córdoba",
    location: "Córdoba",
    sector: "piscinas",
    featured: true,
    legacy: "piscinacordoba",
    images: [
      { src: "/images/obras/piscina-de-cordoba/01.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-cordoba/02.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-cordoba/03.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-cordoba/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "piscina-de-camas",
    title: "Piscina de Camas",
    location: "Camas (Sevilla)",
    sector: "piscinas",
    featured: false,
    legacy: "piscinacamas",
    images: [
      { src: "/images/obras/piscina-de-camas/01.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-camas/02.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-camas/03.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-camas/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "piscina-de-los-santos",
    title: "Piscina de Los Santos",
    location: "Los Santos de Maimona (Badajoz)",
    sector: "piscinas",
    featured: false,
    legacy: "piscinalossantos",
    images: [
      { src: "/images/obras/piscina-de-los-santos/01.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-los-santos/02.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-los-santos/03.webp", width: 720, height: 480 },
      { src: "/images/obras/piscina-de-los-santos/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "depositos-de-alpechin",
    title: "Depósitos de alpechín",
    location: "",
    sector: "piscinas",
    featured: false,
    legacy: "depositosalpechin",
    images: [
      { src: "/images/obras/depositos-de-alpechin/01.webp", width: 720, height: 480 },
      { src: "/images/obras/depositos-de-alpechin/02.webp", width: 720, height: 480 },
      { src: "/images/obras/depositos-de-alpechin/03.webp", width: 720, height: 480 },
      { src: "/images/obras/depositos-de-alpechin/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "sanchinarro",
    title: "Sanchinarro",
    location: "Madrid",
    sector: "residencial",
    featured: false,
    legacy: "sanchinarro",
    images: [
      { src: "/images/obras/sanchinarro/01.webp", width: 720, height: 480 },
      { src: "/images/obras/sanchinarro/02.webp", width: 720, height: 480 },
      { src: "/images/obras/sanchinarro/03.webp", width: 720, height: 480 },
      { src: "/images/obras/sanchinarro/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "vivienda-en-villanueva-de-la-serena",
    title: "Vivienda en Villanueva de la Serena",
    location: "Villanueva de la Serena (Badajoz)",
    sector: "residencial",
    featured: false,
    legacy: "viviendavillanuevalaserena",
    images: [
      { src: "/images/obras/vivienda-en-villanueva-de-la-serena/01.webp", width: 720, height: 480 },
      { src: "/images/obras/vivienda-en-villanueva-de-la-serena/02.webp", width: 720, height: 480 },
      { src: "/images/obras/vivienda-en-villanueva-de-la-serena/03.webp", width: 720, height: 480 },
      { src: "/images/obras/vivienda-en-villanueva-de-la-serena/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "chorro-de-arena",
    title: "Chorro de arena",
    location: "",
    sector: "tecnicas",
    featured: false,
    legacy: "chorrodearena",
    images: [
      { src: "/images/obras/chorro-de-arena/01.webp", width: 720, height: 480 },
      { src: "/images/obras/chorro-de-arena/02.webp", width: 720, height: 480 },
      { src: "/images/obras/chorro-de-arena/03.webp", width: 720, height: 480 },
      { src: "/images/obras/chorro-de-arena/04.webp", width: 720, height: 480 },
    ],
  },
  {
    slug: "cortes-y-taladros",
    title: "Cortes y taladros",
    location: "",
    sector: "tecnicas",
    featured: false,
    legacy: "cortesytaladros",
    images: [
      { src: "/images/obras/cortes-y-taladros/01.webp", width: 720, height: 480 },
      { src: "/images/obras/cortes-y-taladros/02.webp", width: 720, height: 480 },
      { src: "/images/obras/cortes-y-taladros/03.webp", width: 720, height: 480 },
      { src: "/images/obras/cortes-y-taladros/04.webp", width: 720, height: 480 },
    ],
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
